listen_addresses = '*'
max_connections = 100
shared_buffers = 256MB
effective_cache_size = 640MB
work_mem = 8MB
hot_standby = on
hot_standby_feedback = off
max_standby_streaming_delay = 30s
shared_preload_libraries = 'pg_stat_statements'
compute_query_id = on
track_io_timing = on
logging_collector = on
log_destination = 'csvlog'
log_directory = '/var/log/postgresql'
log_filename = 'postgresql'
log_file_mode = 0644
log_min_duration_statement = 500ms
log_checkpoints = on